name: Pull Request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
    - name: install python 3.9 
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - name: checkout code
      uses: actions/checkout@v3
    - name: Check formatting (black)
      run: black . --check
    - name: install python requirements
      run: pip install -r requirements.txt
    - name: make test ebook
      run: python3 make.py --book_name test_books/animal_farm.epub --no_limit --test
    